### PR TITLE
added microservicsesday.com to CNAME

### PR DESCRIPTION
**Pull request by MikeZTaylor**
Hi @Joe8Bit , I've added the CNAME to the main folder with microservicsesday.com in it.

### CODE REVIEW

**Comment by Joe8Bit** [comment]
Thanks @MikeZTaylor but this is done already, it's currently located in the `./static` directory and is copied to the final `./dist/` with Gulp during the build. This folder is then pushed to gh-pages.

Take a look at the `gh-pages` branch for more info

**Comment by ckiss** [comment]
Hi @Joe8Bit, I'm working for Nearform. So we've got a little confused here because we've got some email from Cian saying this:  "all I would need is for you to CNAME the domain you want to use (microservicesday.com?) onto the following github pages URL
http://microservicesday.github.io/website/"

So you already took care of that, right? Are we supposed to do something else? Cheers. Cristi K

**Comment by Joe8Bit** [comment]
@MikeZTaylor I've setup the github pages instance to support a custom domain, but adding the CNAME file in question, all that needs to happen is for someone who has access to the **domain registrar** to direct it using a CNAME record to the github page.,

**Comment by ckiss** [comment]
Hi @Joe8Bit. I got it now. I forwarded the requests for www.microservicesday.com and microservicesday.com towards gh-pages. It should work now.

**Comment by Joe8Bit** [comment]
@MikeZTaylor something seems to have gone wrong, as it's forwarding within a frame, the below is the page source:

``` html


<html><head></head><frameset border="0" rows="100%,*" cols="100%"
            frameborder="no"><frame name="TopFrame"
            scrolling="yes" noresize src="http://microservicesday.github.io/website/"><frame name="BottomFrame" scrolling="no"
            noresize><noframes></noframes></frameset></html>
```

Could you setup a non-framed forward? This will cause lots of issues with Google, accessibility and general front-end performance and responsiveness.

**Comment by ckiss** [comment]
Hi @Joe8Bit it's fixed now. If all it's working fine you can close this PR. Cheers.

**Pull request closed without merging**
